spring:
  h2:
    console:
      enabled: true
  application:
    name: wordspark

  r2dbc:
    url: r2dbc:oracle://oracle-db:1521/xe
    username: system
    password: oracle

  liquibase:
    enabled: true
    change-log: classpath:changelog-master.xml
    url: jdbc:oracle:thin:@oracle-db:1521:xe
    user: system
    password: oracle

server:
  port: 8081

service:
  version: @projectversion@