spring:
  h2:
    console:
      enabled: true

  r2dbc:
    url: r2dbc:oracle://localhost:1521/xe
    username: system
    password: oracle


  liquibase:
    enabled: true
    change-log: classpath:changelog-master.xml
    url: jdbc:oracle:thin:@localhost:1521:xe
    user: system
    password: oracle

server:
  port: 8081