management:
  endpoints:
    web:
      exposure:
        include: health,info
        exclude: metrics
      base-path: /
      path-mapping:
        prometheus: metrics
  endpoint:
    prometheus:
      enabled: 'true'
    health:
      show-details: always
    metrics:
      enabled: 'true'
  metrics:
    export:
      prometheus:
        enabled: 'true'
logging:
  level:
    se:
      telenor: INFO
    root: INFO
    liquibase: INFO
server:
  shutdown: graceful

spring:
  application:
    name: wordspark
  h2:
    console:
      enabled: true
  r2dbc:
    url: r2dbc:h2:mem:///~/db;MODE=PostgreSQL;
    username: sa
    password:
  liquibase:
    enabled: true
    change-log: classpath:changelog-master.xml
    url: jdbc:h2:mem:~/db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    user: sa
    password:
