#================================
# = h2 datasource
# ===============================
#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    url: jdbc:h2:file:~/dasboot
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

#================================
# = Hibernate datasource
# ===============================
spring:
  datasource:
   url: jdbc:mysql://localhost:3306/words?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
   #url: jdbc:mysql://localhost:3306/words
   username: root
   password: Reza1!Reza1!

# ===============================
# = JPA configurations
# ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: false
    database-platform: MYSQL
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

# ===============================
# = Thymeleaf configurations
# ===============================
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
# ===============================
# = Logging configurations
# ===============================
logging:
  level:
    root: INFO
    com.memorynotfound: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

# ===============================
# = Configure uploaded picture size
# ===============================
server:
    port: 9999

